services:
  application:
    image: poyrazemun/quizzapp:latest
    container_name: quizzapp-spring-container
    ports:
      - "8081:8080"
    networks:
      - quizzapp-mysql-network
    environment:
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-server:9092
    depends_on:
      mysqldb:
        condition: service_healthy
      kafka-server:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  mysqldb:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=quizzapp
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - quizzapp-mysql-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  kafka-server:
    image: apache/kafka:4.0.1
    container_name: kafka-server
    ports:
      - "9092:9092"
    networks:
      - quizzapp-mysql-network
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-server:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
networks:
  quizzapp-mysql-network:
    driver: bridge
    name: quizzapp-mysql-network
    external: true
